apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: <Network 이름>
  namespace: <네임스페이스>
spec:
  podSelector:
    matchLabels:
      <key> : <value> # Deployment가 관리하는 Pod를 선택
  policyTypes:
    - Ingress # < 선택 >
    - Egress
    
  ingress: # < 선택 >
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 22 # < 선택 >

  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 443 # < 필수 >
        - port: 80 # < 필수 >
        - port: 53 # < 필수 >
          protocol: TCP # < 필수 >
        - port: 53 # < 필수 >
          protocol: UDP # < 필수 >
